---
title: "Formal analysis -- 3.d Regress genus abundance against days"
subtitle: "All stages and HC"
date: "`r Sys.Date()`"
author: Yue (Gary) Zhang, PhD
output:
  rmdformats::readthedown:
    self_contained: true
    thumbnails: true
    lightbox: true
    gallery: false
    highlight: tango
    code_folding: hide
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = T, message = T,echo = T) 
```


```{r Initiate, results='hide'}
## initiate ---------------------------------------------------------
packages_to_load = c('ggplot2','vegan','ape','stringr','usedist','ggpubr','corrplot',
                     'cowplot','GGally','scales','metagMisc','ggsci','rstatix','wesanderson', 'readxl','tidyr',
                     'phyloseq','DT','plotly','ranacapa','ggrepel','purrr','dplyr','dendextend','lmerTest','Maaslin2',
                     'performance', 'ComplexHeatmap','circlize','forcats','ggalluvial')
invisible(suppressPackageStartupMessages({
    lapply(packages_to_load, library, character.only = TRUE)
}))

#generating color palettes
col1 = wes_palette("Rushmore1")
col2 = wes_palette("GrandBudapest2")
col3 = wes_palette('Darjeeling2')
col21 <- rev(c("tomato1","darkblue","turquoise1","lightblue","darkred","mediumblue","purple","bisque",
               "greenyellow","yellow","violetred2","darkgreen","darkgoldenrod1","deeppink3","cadetblue4",
               "orchid2","seagreen3","purple4","dodgerblue2","red","gray27"))

set.seed(666)
```

```{r functions and image,eval=TRUE}
outdir = "../data/Results_publication_ready"
p.1r = readRDS(file.path(outdir,'phyloseqObj.specimen.deduplicated.correctedMetadata.rarefied.rds'))

source('utils_functions.R')
source('auxiliaries.R')
```


## Regress genus abundance against days since sysmptom onset

Here we only test patients with >= 3 dates available. Duplicates within the same stage (recovery) but were taken at different days so they are also included.

```{r Days post-onset diff}
pheno <- p.1r %>%
  sample_data %>%
  as.matrix %>%
  as.data.frame %>%
  filter(Stage != 'Healthy Volunteers')

# no ID has samples taken at the same day
# pheno %>%
#   group_by(ID) %>%
#   summarize(has_duplicate_days = any(duplicated(daysSinceSymptomOnset))) %>%
#   filter(has_duplicate_days)

# Aggregate daysSinceSymptomOnset for each ID, creating a unique combination of daysSinceSymptomOnset per ID
uniq_sample_per_ID.count <- aggregate(daysSinceSymptomOnset ~ ID, data = pheno, FUN = function(x) paste(sort(unique(x)), collapse = ", ")) %>%
  mutate(num_samples = sapply(strsplit(as.character(daysSinceSymptomOnset), ", "), length))

create_dt(uniq_sample_per_ID.count,'The number of unique samples of each patient along the time course')

tripletPlus.ID = uniq_sample_per_ID.count %>%
  filter(num_samples>=3) %>%
  pull(ID)

psq.tmp= subset_samples(p.1r,ID %in% tripletPlus.ID)
feature = 'Genus'
res_dir = file.path(outdir,'maaslin2','Days_post-onset_tripletPlus')
msl.tmp = run_maaslin(psq.tmp,res_dir = res_dir,feature = feature)
create_dt(msl.tmp[[1]],'Maaslin2 input1: feature table')
create_dt(msl.tmp[[2]],'Maaslin2 input2: phenotype table')
create_dt(msl.tmp[[3]] %>% filter(qval < 0.05),'Maaslin2 results (q <0.05)')

# remove ecoli in plot as it is likely contaminants
plt.df <- msl.tmp[[3]] %>%
  filter(feature != 'Escherichia.Shigella')
plt = plot_lfc(plt.df,0.05,colorpalette = c(daysSinceSymptomOnset	= pal_jco("default")(10)[1]))
print(plt)
ggsave(file.path(outdir,'forestPlot.acrossDays.q0.05.pdf'),width = 4,height = 5)
```